//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustTrack.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SalesManContextEntities : DbContext
    {
        public SalesManContextEntities()
            : base("name=SalesManContextEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_Admin> T_Admin { get; set; }
        public virtual DbSet<T_Appointment> T_Appointment { get; set; }
        public virtual DbSet<T_AppointmentType> T_AppointmentType { get; set; }
        public virtual DbSet<T_Authority> T_Authority { get; set; }
        public virtual DbSet<T_Customer> T_Customer { get; set; }
        public virtual DbSet<T_Department> T_Department { get; set; }
        public virtual DbSet<T_Employee> T_Employee { get; set; }
    }
}
