//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustTrack.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AppointmentColor
    {
        public string appointment_color_value { get; set; }
        public string appointment_color_name { get; set; }
    }
}
