//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustTrack.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Appointment
    {
        public int appointment_id { get; set; }
        public int customer_id { get; set; }
        public int employee_id { get; set; }
        public int appointment_type_id { get; set; }
        public System.DateTime appointment_start_date { get; set; }
        public System.DateTime appointment_end_date { get; set; }
        public byte[] appointment_color { get; set; }
        public string appointment_before_note { get; set; }
        public bool is_done { get; set; }
        public string appointment_after_note { get; set; }
        public bool is_reappointment { get; set; }
        public bool is_offered { get; set; }
        public bool is_ordered { get; set; }
        public bool is_paid { get; set; }
        public bool is_technical_problem { get; set; }
        public bool is_additional_service { get; set; }
    }
}
