//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustTrack.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Customer
    {
        public int customer_id { get; set; }
        public string customer_authorized_1 { get; set; }
        public string customer_authorized_2 { get; set; }
        public string customer_authorized_3 { get; set; }
        public string customer_sector { get; set; }
        public string customer_area { get; set; }
        public string customer_phone { get; set; }
        public string customer_mail { get; set; }
        public string customer_company_name { get; set; }
        public int customer_city_id { get; set; }
        public int customer_district_id { get; set; }
        public string customer_post_code { get; set; }
        public string customer_tax_number { get; set; }
        public string customer_tax_administration { get; set; }
        public string customer_fax { get; set; }
    }
}
