//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustTrack.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Employee
    {
        public int employee_id { get; set; }
        public int department_id { get; set; }
        public int employee_authority_id { get; set; }
        public string employee_username { get; set; }
        public string employee_name { get; set; }
        public string employee_surname { get; set; }
        public string employee_phone { get; set; }
        public string employee_mail { get; set; }
        public byte[] employee_photo { get; set; }
        public string employee_password { get; set; }
    }
}
